fixes
SakuraBurst/miniature-octo-happiness pull request #1
Opened 2023-02-05 19:07 UTC by SakuraBurst

Без понятия как делать graseful shutdown, основывался на https://habr.com/ru/company/timeweb/blog/589167/

2023-02-09 00:14 UTC, SakuraBurst commented
Спустя 5 дней сражения против тестов, я наконец заставил их работать

2023-02-09 06:11 UTC, shmel1k requested changes

2023-02-09 06:11 UTC, shmel1k commented on cmd/gophermart/main.go
> +var currentState appState = -1
Это рейс

2023-02-09 06:11 UTC, shmel1k commented on cmd/gophermart/main.go
> +			cl()
можно цл перетащить на 118 строчку

2023-02-09 06:11 UTC, shmel1k commented on internal/gophermart/controller/orderController.go
> +	return &GopherMartOrderController{repository: table, loyaltyServiceBaseAddress: u, checkOrderQueue: make(chan struct{}, 10)}, nil
Рекомендую заворачивать такие конструкции не в одну строку, а в несколько: так удобнее читать

2023-02-09 06:11 UTC, shmel1k commented on internal/gophermart/controller/orderController.go
> +	if c.isQueueClosed {
рейс

2023-02-09 06:11 UTC, shmel1k commented on internal/gophermart/controller/orderController.go
> +	c.isQueueClosed = true
рейс

2023-02-09 06:11 UTC, shmel1k commented on internal/gophermart/controller/orderController.go
>  		c.loyaltyServiceBaseAddress.Path = ""
Зачем?..

2023-02-09 06:11 UTC, shmel1k commented on internal/gophermart/controller/orderController.go
>  		c.loyaltyServiceBaseAddress.Path = ""
Ну и это, в теории, рейс

2023-02-09 06:11 UTC, shmel1k commented on internal/gophermart/controller/orderController.go
> +				log.Error(err)
А точно ли нужно дальше продолжать?

2023-02-09 06:11 UTC, shmel1k commented on internal/gophermart/repository/repository.go
> +		return nil, nil, nil, nil, err
Лучше обернуть в 
```go
type InitDatabaseResult {
    ....
}
```

Но вообще, лучше для каждого репозитория сделать свой инициализатор.

2023-02-10 06:47 UTC, shmel1k requested changes

2023-02-10 06:47 UTC, shmel1k commented on internal/gophermart/controller/orderController.go
> +	defer c.mu.RUnlock()
Так делать нельзя. Внешний запрос висит под мьютексом

2023-02-10 06:47 UTC, shmel1k commented on internal/gophermart/controller/orderController.go
> +	c.checkOrderQueue <- struct{}{}
Тоже рейс. В теории, если дёрнуть CreateOrder и тут же позвать CloseQueue, можно получить `attempt to write to closed channel`

2023-08-21 00:30 UTC, merged